version: 2
jobs:
  test:
    docker:
      - image: ruby:2.6.2
    steps:
      - checkout
      - run:
          name: Test
          command: rails test

workflows:
  version: 2
  test:
    jobs:
      - test
